name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --onefile main_gui.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: main_gui
        path: dist/main_gui
